apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: devops-college-project
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: devops-college-project
    spec:
      containers:
      - name: devops-college-project
        image: ewhelan/devops_ansible_kb8_pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
