apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: devops-college-project
spec:
  selector:
    app: devops-college-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
