---
- hosts: all
  become: yes

  tasks:

    - name: stop current running container
      command: docker stop devops-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm devops-container
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi ewhelan/devops_ansible_pipeline:latest
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull ewhelan/devops_ansible_pipeline:latest

    - name: creating docker container using simple-devops-image
      command: docker run -d --name devops-container -p 8080:8080 ewhelan/devops_ansible_pipeline:latest
